Repository GSG-G8/API-Weather-W3, pull requests merged in 2020-02, with the labels that each got.

#16 Add search button and style search input
  index.html
  js/dom.js
  style/style.css
Labels: CSS, DOM, HTML, JS, awaiting review

#18 8 unsplash api
  .gitignore
  index.html
  js/dom.js
  js/xhr.js
  style/style.css
Labels: Merge Approved

#28 Api keys and a little of their functions
  js/dom.js
  js/xhr.js
  style/style.css
Labels: awaiting review

#32 Dom the temperature
  index.html
  js/dom.js
Labels: awaiting review

#60 Fix return in arrow functions and use strict equal
  js/dom.js
  js/logic.js
  js/xhr.js
Labels: awaiting review
